services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.elasticsearch
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=/usr/share/elasticsearch/config/certs/instance/instance.key
      - xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/certs/instance/instance.crt
      - xpack.security.http.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certs/instance/instance.key
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certs/instance/instance.crt
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certs/ca/ca.crt
      - path.repo=/snapshots
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - /var/backups/elasticsearch:/snapshots:Z
    networks: [elk]

  kibana:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.kibana
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=/usr/share/kibana/config/certs/ca/ca.crt
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_CERTIFICATE=/usr/share/kibana/config/certs/instance/instance.crt
      - SERVER_SSL_KEY=/usr/share/kibana/config/certs/instance/instance.key
    ports:
      - "5601:5601"
    depends_on: [elasticsearch]
    networks: [elk]

  logstash:
    build:
      context: .
      dockerfile: Dockerfiles/Dockerfile.logstash
    container_name: logstash
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "5000:5000"
      - "5044:5044"
    depends_on: [elasticsearch]
    networks: [elk]

networks:
  elk:

volumes:
  esdata:
